CREATE DATABASE	QuanLyQuayThuoc
ON PRIMARY 
(
	NAME = 'QLQT_DATA',
	FILENAME='D:\QuanLyQuayThuoc\QLQT_DATA.MDF',
	SIZE = 10,
	MAXSIZE = 100,
	FILEGROWTH = 1
)
LOG ON
(
	NAME = 'QLQT_LOG',
	FILENAME='D:\QuanLyQuayThuoc\QLQT_LOG.LDF',
	SIZE = 10,
	MAXSIZE = 100,
	FILEGROWTH = 1
)
/*Tạo Mã Khách Hàng Tự Động*/
CREATE FUNCTION AUTO_IDKH()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MAKH) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAKH, 3)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Khách Hàng*/
CREATE TABLE KhachHang
(
	MAKH CHAR(5) PRIMARY KEY CONSTRAINT IDKH DEFAULT DBO.AUTO_IDKH(),
	TENKH NVARCHAR(30) NOT NULL,
	GIOITINH NVARCHAR(5) NOT NULL,
	NGAYSINH date,
	EMAIL CHAR(30),
	DIENTHOAI CHAR(12),
	CMND INT,
	DIACHI NVARCHAR(40),
)
CREATE PROC select_KH
as
	SELECT * FROM [dbo].[KhachHang]


/*Tạo Mã Chức Vụ Tự Động*/
CREATE FUNCTION AUTO_IDCV()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MACV) FROM CHUCVU) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MACV, 3)) FROM CHUCVU
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'CV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'CV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Chức Vụ*/
CREATE TABLE ChucVu
(
	MACV CHAR(5) PRIMARY KEY CONSTRAINT IDCV DEFAULT DBO.AUTO_IDCV(),
	TENCV NVARCHAR(30) NOT NULL,
	HESOLUONG FLOAT
)
CREATE PROC select_CV
as
	SELECT * FROM [dbo].[ChucVu]

/*Tạo Mã Nhân Viên Tự Động*/
CREATE FUNCTION AUTO_IDNV()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MANV) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MANV, 3)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Nhân Viên*/
CREATE TABLE NhanVien
(
	MANV CHAR(5) PRIMARY KEY CONSTRAINT IDNV DEFAULT DBO.AUTO_IDNV(),
	MACV CHAR(5) NOT NULL,
	CONSTRAINT fk_MaChucVu
	FOREIGN KEY(MACV)
	REFERENCES CHUCVU(MACV)
	ON DELETE CASCADE ON UPDATE CASCADE,
	TENNV NVARCHAR(30) NOT NULL,
	GIOITINH NVARCHAR(5) NOT NULL,
	NGAYSINH DATE,
	EMAIL CHAR(30),
	DIENTHOAI CHAR(12),
	CMND INT,
	DIACHI NVARCHAR(40),
	NGAYVAOLAM DATE,
)
/*Tạo Proceduce Lấy Danh Sách Nhân Viên*/
CREATE PROC select_NV
as
	SELECT * FROM [dbo].[NhanVien]

/*Tạo Mã Loại Thuốc Tự Động*/
CREATE FUNCTION AUTO_IDLT()
RETURNS VARCHAR(5)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MALOAI) FROM LOAITHUOC) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MALOAI, 3)) FROM LOAITHUOC
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'LT00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'LT0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Loại Thuốc*/
CREATE TABLE LoaiThuoc
(
	MALOAI CHAR(5) PRIMARY KEY CONSTRAINT IDLT DEFAULT DBO.AUTO_IDLT(),
	TENLOAI NVARCHAR(30) NOT NULL,
)
CREATE PROC select_LT
as
	SELECT * FROM [dbo].[LoaiThuoc]


/*Tạo Mã Thuốc Tự Động*/
CREATE FUNCTION AUTO_IDT()
RETURNS VARCHAR(4)
AS
BEGIN
	DECLARE @ID VARCHAR(4)
	IF (SELECT COUNT(MAT) FROM THUOC) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAT, 3)) FROM THUOC
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'T00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'T0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Linh Kiện*/
CREATE TABLE Thuoc
(
	MAT CHAR(4) PRIMARY KEY CONSTRAINT IDT DEFAULT DBO.AUTO_IDT(),
	MALOAI CHAR(5) NOT NULL,
	CONSTRAINT fk_MaLoai
	FOREIGN KEY(MALOAI)
	REFERENCES LOAITHUOC(MALOAI)
	ON DELETE CASCADE ON UPDATE CASCADE,
	TENTHUOC NVARCHAR(30) NOT NULL,
	THANHPHAN NVARCHAR(100),
	CONGDUNG NVARCHAR(50) NOT NULL,
	DONVITINH NVARCHAR(70),
	XUATXU NVARCHAR(50),
	SOLUONG INT,
	GIABAN FLOAT,
	NGAYHETHAN DATE,
)

CREATE PROC select_T
as
	SELECT * FROM [dbo].[Thuoc]


/*HoaDon,PhieuNhap,BaoHanh*/
CREATE FUNCTION AUTO_IDNCC()
RETURNS VARCHAR(6)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MANHACC) FROM NHACUNGCAP) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MANHACC, 3)) FROM NHACUNGCAP
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NCC00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NCC0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
/*Bảng Nhân Viên*/
CREATE TABLE NhaCungCap
(
	MANHACC CHAR(6) PRIMARY KEY CONSTRAINT IDNCC DEFAULT DBO.AUTO_IDNCC(),
	TENNHACC NVARCHAR(30) NOT NULL,
	DIACHI NVARCHAR(50) NOT NULL,
	SODT CHAR(30) NOT NULL,
	EMAIL CHAR(30) NOT NULL
)

CREATE PROC select_NCC
as
	SELECT * FROM [dbo].[NhaCungCap]

/*HoaDonBanHang*/
CREATE FUNCTION AUTO_IDHDBH()
RETURNS VARCHAR(7)
AS
BEGIN
	DECLARE @ID VARCHAR(7)
	IF (SELECT COUNT(MAHDBH) FROM HOADONBANHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAHDBH, 3)) FROM HOADONBANHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDBH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDBH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE HoaDonBanHang
(
	MaHDBH CHAR(7) PRIMARY KEY CONSTRAINT IDHDBH DEFAULT DBO.AUTO_IDHDBH(),
	MAKH CHAR(5) NOT NULL,
	MANV CHAR(5) NOT NULL,
	NGAYLAPHD DATE,
	TONGTIEN FLOAT,
	CONSTRAINT fk_MaKHMH
	FOREIGN KEY(MAKH)
	REFERENCES KHACHHANG(MAKH)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_MaNV
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN(MANV)
	ON DELETE CASCADE ON UPDATE CASCADE,
)
/*CT*/
CREATE TABLE CT_HoaDonBanHang
(
	MaHDBH CHAR(7) NOT NULL,
	MAT CHAR(4) NOT NULL,
	SOLUONG INT,
	DONGIA FLOAT,
	CONSTRAINT pk_CTHDBH
	PRIMARY KEY(MAHDBH,MAT),
	CONSTRAINT fk_MaHDBH
	FOREIGN KEY(MAHDBH)
	REFERENCES HOADONBANHANG(MAHDBH)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_MALKB
	FOREIGN KEY(MAT)
	REFERENCES THUOC(MAT)
	ON DELETE CASCADE ON UPDATE CASCADE,
)
CREATE FUNCTION AUTO_IDHDNH()
RETURNS VARCHAR(7)
AS
BEGIN
	DECLARE @ID VARCHAR(7)
	IF (SELECT COUNT(MAHDNH) FROM HOADONNHAPHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MAHDNH, 3)) FROM HOADONNHAPHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HDNH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HDNH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE HoaDonNhapHang
(
	MaHDNH CHAR(7) PRIMARY KEY CONSTRAINT IDHDNH DEFAULT DBO.AUTO_IDHDNH(),
	MANHACC CHAR(6) NOT NULL,
	MANV CHAR(5) NOT NULL,
	NGAYLAPHD DATE,
	TONGTIEN FLOAT,
	CONSTRAINT fk_MaNCCLK
	FOREIGN KEY(MANHACC)
	REFERENCES NHACUNGCAP(MANHACC)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_MaNVNH
	FOREIGN KEY(MANV)
	REFERENCES NHANVIEN(MANV)
	ON DELETE CASCADE ON UPDATE CASCADE,
)
CREATE TABLE CT_HoaDonNhapHang
(
	MaHDNH CHAR(7) NOT NULL,
	MAT CHAR(4) NOT NULL,
	SOLUONG INT,
	DONGIA FLOAT,
	CONSTRAINT pk_CTHDNH
	PRIMARY KEY(MAHDNH,MAT),
	CONSTRAINT fk_MaHDNH
	FOREIGN KEY(MAHDNH)
	REFERENCES HOADONNHAPHANG(MAHDNH)
	ON DELETE CASCADE ON UPDATE CASCADE,
	CONSTRAINT fk_MALKN
	FOREIGN KEY(MAT)
	REFERENCES THUOC(MAT)
	ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE TaiKhoan
(
	TENDN CHAR(15) NOT NULL PRIMARY KEY,
	MATKHAU CHAR(30) NOT NULL,
	MA CHAR(7) NOT NULL,
	TEN NVARCHAR(40) NOT NULL,
	QUYEN NVARCHAR(50) NOT NULL
)

INSERT INTO [dbo].[KhachHang]([TENKH],[GIOITINH],[NGAYSINH],[EMAIL],[DIENTHOAI],[CMND],[DIACHI])
VALUES(N'Nguyễn Văn Hùng','Nam','2000-04-25','hungcoder254@gmail.com','096969999',13489654,N'Gò Vấp, TP.Hồ Chí Minh')

INSERT INTO [dbo].[ChucVu]([TENCV],[HESOLUONG])
VALUES(N'Nhân Viên Kinh Doanh',2.0)

INSERT INTO [dbo].[NhanVien]([MACV],[TENNV],[GIOITINH],[NGAYSINH],[EMAIL],[DIENTHOAI],[CMND],[DIACHI],[NGAYVAOLAM])
VALUES('CV001',N'Nguyễn Văn Hùng','Nam','2000-04-25','hungcoder254@gmail.com','096969999',13489654,N'Gò Vấp, TP.Hồ Chí Minh','2020-01-20')

INSERT INTO [dbo].[NhaCungCap]([TENNHACC],[DIACHI],[SODT],[EMAIL])
VALUES('Pharmacity',N'Hồ Chí Minh','098888888','pharmacity@gmail.com')

INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Kháng Dị Ứng')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Kháng Viêm')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Cảm Lạnh,Ho')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Da Liễu')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Giảm Cân')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Thần Kinh')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Giảm Đau, Hạ Sốt')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Tiêu Hóa')
INSERT INTO [dbo].[LoaiThuoc]([TENLOAI])
VALUES(N'Thuốc Cơ Xương Khớp')

INSERT INTO [dbo].[Thuoc]([MALOAI],[TENTHUOC],[THANHPHAN],[CONGDUNG],[DONVITINH],[XUATXU],[SOLUONG],[GIABAN],[NGAYHETHAN])
VALUES('LT001','Zyrtec','',N'Kháng Dị Ứng','Hộp','Anh',10,80000,'2000-08-22')

SELECT hd.MaHDBH,hd.NGAYLAPHD,nv.TENNV,kh.TENKH,kh.DIACHI,kh.DIENTHOAI,kh.EMAIL,kh.GIOITINH,
t.TENTHUOC,lt.TENLOAI,t.CONGDUNG,t.DONVITINH,ct.SOLUONG,t.GIABAN,ct.SOLUONG*t.GIABAN AS ThanhTien
FROM [dbo].[HoaDonBanHang] hd JOIN [dbo].[CT_HoaDonBanHang] ct ON hd.MaHDBH = ct.MaHDBH
JOIN [dbo].[NhanVien] nv ON hd.MANV = nv.MANV
JOIN [dbo].[KhachHang] kh ON hd.MAKH = kh.MAKH
JOIN [dbo].[Thuoc] t ON ct.MAT = t.MAT
JOIN [dbo].[LoaiThuoc] lt ON t.MALOAI = lt.MALOAI
WHERE hd.MaHDBH = 'HDBH001'


SELECT hd.MaHDNH,hd.NGAYLAPHD,nv.TENNV,ncc.TENNHACC,ncc.SODT,ncc.EMAIL,ncc.DIACHI,t.TENTHUOC,t.CONGDUNG,t.DONVITINH,t.GIABAN,t.NGAYHETHAN,
ct.SOLUONG,t.THANHPHAN,lt.TENLOAI
FROM [dbo].[HoaDonNhapHang] hd JOIN [dbo].[CT_HoaDonNhapHang] ct  ON hd.MaHDNH = ct.MaHDNH
JOIN [dbo].[NhanVien] nv ON hd.MANV = nv.MANV
JOIN [dbo].[NhaCungCap] ncc ON hd.MANHACC = ncc.MANHACC
JOIN [dbo].[Thuoc] t ON ct.MAT = t.MAT
JOIN [dbo].[LoaiThuoc] lt ON t.MALOAI = lt.MALOAI
WHERE hd.MaHDNH = 'HDNH014'

SELECT *
FROM [dbo].[Thuoc] t WHERE t.MAT IN (SELECT ct.MAT FROM 
[dbo].[CT_HoaDonBanHang] ct JOIN [dbo].[HoaDonBanHang] 
hd ON ct.MaHDBH = hd.MaHDBH WHERE DAY(hd.NGAYLAPHD) = DAY(GETDATE()))
SELECT t.MAT,t.TENTHUOC,lt.TENLOAI,t.CONGDUNG,t.DONVITINH,t.SOLUONG,t.GIABAN,t.GIABAN*t.SOLUONG AS THANHTIEN
FROM [dbo].[Thuoc] t JOIN [dbo].[LoaiThuoc] lt ON t.MALOAI = lt.MALOAI